controle-estoque/ControleEstoque.Web/Controllers/Cadastro/CadMarcaProdutoController.cs
using AutoMapper;
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    [Authorize(Roles = "Gerente,Administrativo,Operador")]
    public class CadMarcaProdutoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = Mapper.Map<List<MarcaProdutoViewModel>>(MarcaProdutoModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina));
            var quant = MarcaProdutoModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;

            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult MarcaProdutoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = Mapper.Map<List<MarcaProdutoViewModel>>(MarcaProdutoModel.RecuperarLista(pagina, tamPag, filtro, ordem));

            return Json(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarMarcaProduto(int id)
        {
            var vm = Mapper.Map<MarcaProdutoViewModel>(MarcaProdutoModel.RecuperarPeloId(id));

            return Json(vm);
        }

        [HttpPost]
        [Authorize(Roles = "Gerente,Administrativo")]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirMarcaProduto(int id)
        {
            return Json(MarcaProdutoModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarMarcaProduto(MarcaProdutoViewModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var vm = Mapper.Map<MarcaProdutoModel>(model);
                    var id = vm.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

controle-estoque/ControleEstoque.Web/Views/CadMarcaProduto/Index.cshtml
@model List<ControleEstoque.Web.Models.MarcaProdutoViewModel>
@{
    Layout = "~/Views/Shared/_Cadastro.cshtml";
    ViewBag.Title = "Marca de Produtos";
    ViewBag.Lista = Model;
}

@section Styles {
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/Cadastro/MarcaProduto.css" rel="stylesheet" />
}

@section TituloGrid {
    <th><span class="coluna-ordenacao" data-campo="nome">Nome</span></th>
    <th><span class="coluna-ordenacao" data-campo="ativo">Ativo</span></th>
    <th>Ação</th>
}

@section CamposCadastro {
    <div class="row">
        <div class="col-md-12">
            @Html.Label("txt_nome", "Nome", new { @class = "control-label" })
            @Html.TextBox("txt_nome", null, new { @class = "form-control" })
        </div>
    </div>
    <div class="row" style="margin-top: 15px">
        <div class="col-md-12">
            <div class="form-check">
                @Html.CheckBox("cbx_ativo", new { @class = "form-check-input" })
                @Html.Label("cbx_ativo", "Ativo", new { @class = "form-check-label" })
            </div>
        </div>
    </div>
}

@section Scripts{
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script>
        var tituloPagina = '@ViewBag.Title';
        var url_excluir = '@Url.Action("ExcluirMarcaProduto", "CadMarcaProduto")';
        var url_confirmar = '@Url.Action("SalvarMarcaProduto", "CadMarcaProduto")';
        var url_page_click = '@Url.Action("MarcaProdutoPagina", "CadMarcaProduto")';
        var url_filtro_change = '@Url.Action("MarcaProdutoPagina", "CadMarcaProduto")';
        var url_tam_pag_change = '@Url.Action("MarcaProdutoPagina", "CadMarcaProduto")';
        var url_alterar = '@Url.Action("RecuperarMarcaProduto", "CadMarcaProduto")';
        var linhas = [];

        @{
            var linha = 0;
            foreach (var item in Model)
            {
                linha++;
                if (linha <= ViewBag.QuantMaxLinhasPorPagina)
                {
                    @:linhas.push(@Html.Raw(Json.Encode(item)));
                                                }
                else
                {
                    break;
                }
            }
        }
    </script>
    <script id="template-grid" type="x-tmpl-mustache">
        <tr data-id="{{ Id }}">
            <td>{{ Nome }}</td>
            <td>{{ #Ativo }}SIM{{ /Ativo }}{{ ^Ativo }}NÃO{{ /Ativo }}</td>
            <td>
                <a class="btn btn-primary btn-alterar" role="button"><i class="glyphicon glyphicon-pencil"></i> Alterar</a>
                <a class="btn btn-danger btn-excluir" role="button"><i class="glyphicon glyphicon-trash"></i> Excluir</a>
            </td>
        </tr>
    </script>
    <script src="~/Scripts/Cadastro/MarcaProduto.js"></script>
}